<?php
// install.php - Simple Installer for Hostinger
error_reporting(E_ALL);
ini_set('display_errors', 1);

$configFile = __DIR__ . '/config.php';
$schemaFile = __DIR__ . '/install.sql';

$message = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = $_POST['host'] ?? 'localhost';
    $user = $_POST['user'] ?? '';
    $pass = $_POST['pass'] ?? '';
    $name = $_POST['name'] ?? '';

    // Test Connection
    $mysqli = new mysqli($host, $user, $pass, $name);

    if ($mysqli->connect_error) {
        $message = '<div class="error">Connection Failed: ' . $mysqli->connect_error . '</div>';
    } else {
        // Connection Successful

        // 1. Write config.php
        $configContent = "<?php
// config.php - auto-generated by install.php
return [
    'db'=>[
        'host'=>'" . addslashes($host) . "',
        'user'=>'" . addslashes($user) . "',
        'pass'=>'" . addslashes($pass) . "',
        'name'=>'" . addslashes($name) . "',
        'port'=>3306
    ],
    // Admin credentials (fallback)
    'admin_user'=>'admin',
    'admin_pass'=>'admin123',
    // Upload folders
    'upload_dir'=>'public/uploads',
    // GST
    'default_gst'=>18.00
];
";
        if (file_put_contents($configFile, $configContent)) {

            // 2. Import Schema
            if (file_exists($schemaFile)) {
                $sql = file_get_contents($schemaFile);
                if ($mysqli->multi_query($sql)) {
                    do {
                        // Consume all results
                        if ($res = $mysqli->store_result()) {
                            $res->free();
                        }
                    } while ($mysqli->more_results() && $mysqli->next_result());

                    $message = '<div class="success">
                        <h2>Installation Successful!</h2>
                        <p>Database connected and schema imported.</p>
                        <p><strong>Security Warning:</strong> Please delete <code>install.php</code> and <code>install.sql</code> now.</p>
                        <a href="index.php" class="btn">Go to Website</a>
                        <a href="admin/login.php" class="btn">Go to Admin Login</a>
                    </div>';
                } else {
                    $message = '<div class="error">Schema Import Failed: ' . $mysqli->error . '</div>';
                }
            } else {
                $message = '<div class="error">install.sql format not found!</div>';
            }

        } else {
            $message = '<div class="error">Could not write to config.php. Check permissions.</div>';
        }

        $mysqli->close();
    }
}
?>
<!DOCTYPE html>
<html>

<head>
    <title>Hotel App Installer</title>
    <style>
        body {
            font-family: sans-serif;
            background: #f4f4f4;
            padding: 20px;
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .group {
            margin-bottom: 15px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            width: 100%;
            padding: 12px;
            background: #20B2AA;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

        button:hover {
            background: #1a9b94;
        }

        .error {
            background: #fee;
            color: #c00;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 20px;
        }

        .success {
            background: #eef;
            color: #009;
            padding: 20px;
            border-radius: 4px;
            text-align: center;
        }

        .btn {
            display: inline-block;
            margin: 10px 5px;
            padding: 10px 20px;
            background: #333;
            color: white;
            text-decoration: none;
            border-radius: 4px;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>App Installer</h1>
        <?= $message ?>

        <?php if (strpos($message, 'Success') === false): ?>
            <form method="post">
                <div class="group">
                    <label>Database Host</label>
                    <input type="text" name="host" value="localhost" required>
                </div>
                <div class="group">
                    <label>Database Username</label>
                    <input type="text" name="user" placeholder="u123456789_admin" required>
                </div>
                <div class="group">
                    <label>Database Password</label>
                    <input type="password" name="pass" required>
                </div>
                <div class="group">
                    <label>Database Name</label>
                    <input type="text" name="name" placeholder="u123456789_hotel" required>
                </div>
                <button type="submit">Install & Import Database</button>
            </form>
        <?php endif; ?>
    </div>
</body>

</html>